// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SubsonicWeb {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Panel pnlLogin;
		
		protected System.Web.UI.WebControls.Label lblUsername;
		
		protected System.Web.UI.WebControls.TextBox tbUsername;
		
		protected System.Web.UI.WebControls.Label lblPassword;
		
		protected System.Web.UI.WebControls.TextBox tbPassword;
		
		protected System.Web.UI.WebControls.Button btnLogIn;
	}
}
