// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SubsonicWeb {
	
	
	public partial class Library {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Repeater rptArtists;
		
		protected System.Web.UI.WebControls.LinkButton lbtnArtist;
		
		protected System.Web.UI.WebControls.HyperLink hlnkArtist;
		
		protected System.Web.UI.WebControls.Label lblSelArtist;
		
		protected System.Web.UI.WebControls.Repeater rptItems;
	}
}
