
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed frMain;

	private global::Gtk.Label lblTitle;

	private global::Gtk.Entry tbServer;

	private global::Gtk.Label lbServer;

	private global::Gtk.Label lblUsername;

	private global::Gtk.Entry tbUsername;

	private global::Gtk.Label lbPassw00rd;

	private global::Gtk.Entry tbPaassw0rd;

	private global::Gtk.ScrolledWindow swLibrary;

	private global::Gtk.Button btnLogin2;

	private global::Gtk.ScrolledWindow swPlayQueue;

	private global::Gtk.Button btnQueueSong;

	private global::Gtk.Button btnSearch;

	private global::Gtk.Entry tbSearch;

	private global::Gtk.Label label1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.frMain = new global::Gtk.Fixed ();
		this.frMain.Name = "frMain";
		this.frMain.HasWindow = false;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.lblTitle = new global::Gtk.Label ();
		this.lblTitle.Name = "lblTitle";
		this.lblTitle.LabelProp = global::Mono.Unix.Catalog.GetString ("Subsonic");
		this.frMain.Add (this.lblTitle);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.lblTitle]));
		w1.X = 9;
		w1.Y = 10;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.tbServer = new global::Gtk.Entry ();
		this.tbServer.CanFocus = true;
		this.tbServer.Name = "tbServer";
		this.tbServer.IsEditable = true;
		this.tbServer.InvisibleChar = '•';
		this.frMain.Add (this.tbServer);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.tbServer]));
		w2.X = 9;
		w2.Y = 71;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.lbServer = new global::Gtk.Label ();
		this.lbServer.Name = "lbServer";
		this.lbServer.LabelProp = global::Mono.Unix.Catalog.GetString ("Server URL:");
		this.frMain.Add (this.lbServer);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.lbServer]));
		w3.X = 13;
		w3.Y = 46;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.lblUsername = new global::Gtk.Label ();
		this.lblUsername.Name = "lblUsername";
		this.lblUsername.LabelProp = global::Mono.Unix.Catalog.GetString ("Username:");
		this.frMain.Add (this.lblUsername);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.lblUsername]));
		w4.X = 15;
		w4.Y = 110;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.tbUsername = new global::Gtk.Entry ();
		this.tbUsername.CanFocus = true;
		this.tbUsername.Name = "tbUsername";
		this.tbUsername.IsEditable = true;
		this.tbUsername.InvisibleChar = '•';
		this.frMain.Add (this.tbUsername);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.tbUsername]));
		w5.X = 11;
		w5.Y = 138;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.lbPassw00rd = new global::Gtk.Label ();
		this.lbPassw00rd.Name = "lbPassw00rd";
		this.lbPassw00rd.LabelProp = global::Mono.Unix.Catalog.GetString ("Password:");
		this.frMain.Add (this.lbPassw00rd);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.lbPassw00rd]));
		w6.X = 13;
		w6.Y = 176;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.tbPaassw0rd = new global::Gtk.Entry ();
		this.tbPaassw0rd.CanFocus = true;
		this.tbPaassw0rd.Name = "tbPaassw0rd";
		this.tbPaassw0rd.IsEditable = true;
		this.tbPaassw0rd.Visibility = false;
		this.tbPaassw0rd.InvisibleChar = '•';
		this.frMain.Add (this.tbPaassw0rd);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.tbPaassw0rd]));
		w7.X = 13;
		w7.Y = 199;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.swLibrary = new global::Gtk.ScrolledWindow ();
		this.swLibrary.WidthRequest = 262;
		this.swLibrary.HeightRequest = 348;
		this.swLibrary.CanFocus = true;
		this.swLibrary.Name = "swLibrary";
		this.swLibrary.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frMain.Add (this.swLibrary);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.swLibrary]));
		w8.X = 10;
		w8.Y = 295;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.btnLogin2 = new global::Gtk.Button ();
		this.btnLogin2.CanFocus = true;
		this.btnLogin2.Name = "btnLogin2";
		this.btnLogin2.UseUnderline = true;
		this.btnLogin2.Label = global::Mono.Unix.Catalog.GetString ("Login2");
		this.frMain.Add (this.btnLogin2);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.btnLogin2]));
		w9.X = 14;
		w9.Y = 241;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.swPlayQueue = new global::Gtk.ScrolledWindow ();
		this.swPlayQueue.WidthRequest = 208;
		this.swPlayQueue.HeightRequest = 338;
		this.swPlayQueue.CanFocus = true;
		this.swPlayQueue.Name = "swPlayQueue";
		this.swPlayQueue.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frMain.Add (this.swPlayQueue);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.swPlayQueue]));
		w10.X = 315;
		w10.Y = 296;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.btnQueueSong = new global::Gtk.Button ();
		this.btnQueueSong.CanFocus = true;
		this.btnQueueSong.Name = "btnQueueSong";
		this.btnQueueSong.UseUnderline = true;
		this.btnQueueSong.Label = global::Mono.Unix.Catalog.GetString (">");
		this.frMain.Add (this.btnQueueSong);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.btnQueueSong]));
		w11.X = 280;
		w11.Y = 425;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.btnSearch = new global::Gtk.Button ();
		this.btnSearch.CanFocus = true;
		this.btnSearch.Name = "btnSearch";
		this.btnSearch.UseUnderline = true;
		this.btnSearch.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.frMain.Add (this.btnSearch);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.btnSearch]));
		w12.X = 323;
		w12.Y = 247;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.tbSearch = new global::Gtk.Entry ();
		this.tbSearch.CanFocus = true;
		this.tbSearch.Name = "tbSearch";
		this.tbSearch.IsEditable = true;
		this.tbSearch.InvisibleChar = '•';
		this.frMain.Add (this.tbSearch);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.tbSearch]));
		w13.X = 315;
		w13.Y = 213;
		// Container child frMain.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
		this.frMain.Add (this.label1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.frMain[this.label1]));
		w14.X = 318;
		w14.Y = 179;
		this.Add (this.frMain);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 836;
		this.DefaultHeight = 684;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnLogin2.Clicked += new global::System.EventHandler (this.OnBtnLogin2Clicked);
		this.btnQueueSong.Clicked += new global::System.EventHandler (this.OnBtnQueueSongClicked);
		this.btnSearch.Clicked += new global::System.EventHandler (this.OnBtnSearchClicked);
	}
}
